name: Auto Deploy to Render

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: |
        echo "Running pre-deployment checks..."
        node --version
        npm --version
        npm audit --audit-level moderate
    
    - name: Trigger Render Deployment
      run: |
        echo "🚀 Triggering Render deployment..."
        echo "Render will automatically deploy when push is detected"
        echo "Make sure your Render service is connected to this GitHub repository"
    
    - name: Deployment Status
      run: |
        echo "✅ Deployment triggered successfully!"
        echo "📊 Check Render dashboard for deployment status"