name: Test and Lint

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Check Node.js version
      run: node --version && npm --version
    
    - name: Validate package.json
      run: npm pack --dry-run
    
    - name: Check for syntax errors
      run: |
        echo "Checking JavaScript files for syntax errors..."
        find . -name "*.js" -not -path "./node_modules/*" -exec node -c {} \;
    
    - name: Check HTML files
      run: |
        echo "Checking HTML files..."
        find . -name "*.html" -not -path "./node_modules/*" -exec echo "Checking {}" \;

  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run npm audit
      run: npm audit --audit-level moderate
      continue-on-error: true